server:
  port: 6001
  servlet:
    context-path: /items
spring:
  application:
    name: items
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 115MB
  datasource:
    url: "jdbc:postgresql://localhost:5432/bidbig"
    username: "bdbadmin"
    password: "123456"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL94Dialect"
        ddl-auto: create
        default_schema: "${spring.application.name}"
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: true
file:
  upload-dir: "./items/src/main/resources/item-images"