security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: https://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  # data:
  #   mongodb:
  #     host: account-mongodb
  #     username: user
  #     password: ${MONGODB_PASSWORD}
  #     database: piggymetrics
  #     port: 27017
  datasource:
    url: jdbc:postgresql://postgresql:5432/liveauction
    username: postgres
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
      hibernate:
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: false


server:
  servlet:
    context-path: /accounts
  port: 6000
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: black123
    key-store-type: JKS
    # trust-store: classpath:truststore.jks
    # trust-store-type: JKS
    # trust-store-password: changeit
    key-alias: account-service

feign:
  hystrix:
    enabled: true
  # okhttp:
  #   enabled: true