logging:
  level:
    org.springframework.security: DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  instance:
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    statusPageUrl: https://localhost:${server.port}/info
    healthCheckUrl: https://localhost:${server.port}/health
    homePageUrl: https://localhost:${server.port}
  client:
    serviceUrl:
      defaultZone: https://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: https://auth-service:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq

feign:
  client:
    config:
      default:
        connectTimeout: 20000
        readTimeout: 20000

management:
  endpoints:
    web:
      exposure:
        include: "*"  #<2>
  endpoint:
    health:
      show-details: ALWAYS