hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
  IsSecure: true
  # key-store: classpath:gateway.p12
  # key-store-password: black123
  # trust-store: classpath:cacerts
  # trust-store-password: black123
  # key-alias: gateway

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  debug:
    request: true

  routes:
    auth-service:
        path: /uaa/**
        url: https://auth-service:5000
        stripPrefix: false
        sensitiveHeaders:

    account-service:
        path: /accounts/**
        url: https://account-service:6000
        stripPrefix: false
        sensitiveHeaders:

    notification-service:
        path: /notifications/**
        serviceId: notification-service
        stripPrefix: false
        sensitiveHeaders:

    bidding:
      path: /bids/**
      serviceId: bidding
      stripPrefix: false
      sensitiveHeaders:

    auction-service:
        path: /auctions/**
        serviceId: auction-service
        stripPrefix: false
        sensitiveHeaders:

    items-service:
        path: /items/**
        serviceId: items-service
        stripPrefix: false
        sensitiveHeaders:

server:
  port: 4000
  ssl:
    enabled: false
    # key-store: classpath:gateway.p12
    # key-store-password: black123
    # trust-store: classpath:truststore.jks
    # trust-store-type: JKS
    # trust-store-password: changeit
  compression:
    enabled: true
    mime-types: text/css,application/json,application/xml,text/html,text/xml,text/plain,application/javascript,image/gif,image/jpeg
