server:
  port: 8761
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: black123
    trust-store: classpath:cacerts
    trust-store-password: black123
    key-alias: eureka